//
// Created by vladb on 4/19/2023.
//

#ifndef INCE_O_MULTIME_CU_RELATIE_MYTESTULETZ_H
#define INCE_O_MULTIME_CU_RELATIE_MYTESTULETZ_H


void run_my_teste();


#endif //INCE_O_MULTIME_CU_RELATIE_MYTESTULETZ_H
