-- solutie: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM Client
WAITFOR DELAY '00:00:10'
SELECT * FROM Client
COMMIT TRAN


DELETE FROM Client
WHERE Nume = 'Goofer' AND email = 'gooferman@gmail.com';


select * from Client