-- solutie: SET TRANSACTION ISOLATION LEVEL READ COMMITTED--

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
SELECT * FROM reducere
WAITFOR DELAY '00:00:10'
SELECT * FROM reducere
COMMIT TRAN